### ISSUE TITLE
Set Meetify profile pic the same as spotify pic

### ISSUE THREAD

**Issue by RobBoeckermann** [RobBoeckermann/Meetify#30]
low priority

`sp = spotipy.Spotify(request.session['sp_token']['access_token'])
    user = User_Info.objects.get(pk=request.user.pk)
    data = sp.user(user.SpotifyUserId)
    print(data['images'][0]['url'])`

The above code can be used.

**Comment by segeeslice** [comment]
I presume this would imply we cannot change the profile picture from the front-end then?
